# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Shiv Narayan Pandey
description: >- # this means to ignore newlines until "baseurl:"
  Guiding the students in their studies as well as towards spritiual platform also.
baseurl: # the subpath of the site
url: "https://shivnp.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog
    - name: News

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: harekrishnasn@gmail.com
      link: mailto:harekrishnasn@gmail.com

  follow:
    - name: Facebook
      link: https://www.facebook.com/profile.php?id=100008707202396
    - name: GitHub
      link: http://github.com/shivnp


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
